MERGE INTO STATHOSDAYPATIENTAREA SH
USING (
    SELECT TEM.STATDAY,
      TEM.HOSID,
      CASE WHEN INSTR(TEM.IPAREA,'-',1,1)=0 THEN TEM.IPAREA ELSE SUBSTR(TEM.IPAREA,1,INSTR(TEM.IPAREA,'-',1,1)-1) END AS PROVINCE,
      CASE WHEN INSTR(TEM.IPAREA,'-',1,1)=0 THEN '-' ELSE TO_CHAR(SUBSTR(TEM.IPAREA,INSTR(TEM.IPAREA,'-',1,1)+1,LENGTH(TEM.IPAREA))) END AS CITY,
      TEM.PATIENTCOUNT
    FROM (
        SELECT TS.STATDAY,TS.HOSID,TS.IPAREA,COUNT(TS.IPAREA) AS PATIENTCOUNT
        FROM(
            SELECT T.HOSID,T.STATDAY,T.IPAREA,T.PATIENTPERMITNUM,COUNT(T.PATIENTPERMITNUM)
            FROM(
                --时间范围内的问诊数据
                SELECT SDT.NETHOSID AS HOSID,TRUNC(SDT.TREATSHEETTIME,'DD') AS STATDAY,NVL(SDT.IPAREA,'江西省-南昌市') AS IPAREA,SDT.PATIENTPERMITNUM
                FROM SDTREATINFO SDT
                --WHERE SDT.TREATSHEETTIME BETWEEN :STARTDAY AND :ENDDAY
            ) T
            GROUP BY T.HOSID,T.STATDAY,T.IPAREA,T.PATIENTPERMITNUM
        )TS
        GROUP BY TS.STATDAY,TS.HOSID,TS.IPAREA
    ) TEM
) TP
ON (SH.STATDAY=TP.STATDAY AND SH.HOSID=TP.HOSID AND SH.PROVINCE=TP.PROVINCE AND SH.CITY=TP.CITY)
WHEN MATCHED THEN
  UPDATE SET SH.PATIENTCOUNT=TP.PATIENTCOUNT,SH.UPDATETIME=SYSDATE
  WHERE SH.PATIENTCOUNT!=TP.PATIENTCOUNT
WHEN NOT MATCHED THEN
  INSERT (SH.STATDAY,SH.HOSID,SH.PROVINCE,SH.CITY,SH.PATIENTCOUNT,SH.UPDATETIME)
  VALUES(TP.STATDAY,TP.HOSID,TP.PROVINCE,TP.CITY,TP.PATIENTCOUNT,SYSDATE);