--去掉字段默认值
ALTER TABLE ACCOUNT MODIFY(CARDTYPE NUMBER(38) DEFAULT NULL);

--给字段添加CHECK约束
ALTER TABLE ACCOUNT ADD CONSTRAINT CKC_ACCOUNT_CARDTYPE CHECK(CARDTYPE IN(1,2,3,4,5,6,7,99));

--删除约束
ALTER TABLE ACCOUNT DROP CONSTRAINT CKC_COMMONLYUSER_CARDTYPE;

--

